const dataFromDB = [
    {
        name: "Cuchillo Bowie",
        img: ['../assets/Cuchillo_Bowie.jpeg'],
        description: "Cuchillo de 20CM producido con material de disco de arado. Cabo de madera con detalles de acero inoxidable.",
        price: "$7500ars",
        stock: 7,
        id: 1,
        idCategory: 'utensilios',
    },
    {
        name: "Delantal de cocina",
        img: ["../assets/Delantales.jpeg"],
        description: "Distintos diseño de estampa. Confeccionadoa en jean y cuero. Regulable a la altura del cuello y la cintura.",
        price: "$6500ars",
        stock: 4,
        id:2,
        idCategory: 'indumentaria',
    },
    // {
    //     name: "Provoletera",
    //     img: ['../assets/Provoletera.jpeg'],
    //     description: "Provoleteras de aluminio. Disponibles en su version con mango o con base de madera",
    //     price: "$3500ars",
    //     stock: 4,
    //     id:3,
    //     idCategory: 'accesorios',
    // },
    {
        name: "Sacacorchos",
        img: ['../assets/Sacacorchos.jpeg'],
        description: "Sacacorchos de laminas ideal para vinos añejos.",
        price: "$3500ars",
        stock: 4,
        id:4,
        idCategory:'accesorios',
    },
    {
        name: 'Plancheta c/utensillos',
        img: [],
        description:'juego de plancheta, molde para huevos, espatula y pinza.' ,
        price: '$7500ars',
        stock: 3,
        id: 5,
        idCategory:'utensilios',
    },
    {
        name: 'Plancheta',
        img: [],
        description: 'Plancheta de acero. utilizable en tanto en la cocina como en la parrilla.',
        price: '$5000ars',
        stock: 8,
        id: 6,
        idCategory:'accesorios',
    },
    {
        name: 'Pala, pinza y atizador',
        img: [],
        description: 'Juego de herramientas para el asador.',
        price: '$5500',
        stock: 23,
        id: 7,
        idCategory:'accesorios',
    },
    {
        name: 'Afilador',
        img: [],
        description: 'Afilador con piedra de tungsteno. Ideal para cuchillos, tijeras, o cualquier herramienta.',
        price:'$3000ars' ,
        stock: 6,
        id: 8,
        idCategory:'accesorios',
    },
    {
        name: 'Estaca',
        img: [],
        description: 'Estaca tridente con soporte. Soporta hasta 10KG.',
        price: '$7000ars',
        stock: 5,
        id: 9,
        idCategory: 'accesorios',
    },
    {
        name: 'Tabla algarrobo',
        img: [],
        description: 'Tabla de madera de algarrobo.',
        price: '$3800ars',
        stock: 8,
        id: 10,
        idCategory:'accesorios',
    },
    {
        name: 'Tabla grill',
        img: [],
        description: 'Tabla de madera con un grill de alumino para mantener caliente tus comidas.',
        price: '$7500ars',
        stock: 3,
        id: 11,
        idCategory: 'accesorios',
    },

];

export default dataFromDB;
